const { chromium } = require('playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({headless:true,channel:'msedge'});
 try {
 const page = await browser.newPage();
 await page.setContent('<div id="host"></div>');
 await page.addScriptTag({content:fs.readFileSync('public/us-links.js','utf8')});
 await page.addStyleTag({content:fs.readFileSync('public/style.css','utf8')});
 await page.evaluate(() => {
  window.data = {items:[]}; window.saves=[]; window.opens=[];
  window.open = (...args) => window.opens.push(args);
  // setContent has no secure origin, so supply deterministic test IDs.
  let next = 0; crypto.randomUUID = () => 'test-' + (++next);
  const host = document.querySelector('#host'); host.innerHTML=USLinks.layout();
  USLinks.mount(host,()=>window.data,async()=>{saves.push(JSON.parse(JSON.stringify(data)));return true;});
 });
 const click = name => page.getByRole('button',{name,exact:true}).click();
 const fill = async (title,url) => {await page.getByRole('textbox',{name:'제목',exact:true}).fill(title);await page.getByRole('textbox',{name:'URL',exact:true}).fill(url);};
 const state = () => page.evaluate(()=>data.items);
 await click('항목 추가'); await fill('첫 항목','https://example.com/one'); await click('저장');
 const original=(await state())[0]; assert.ok(original.id);
 assert.equal(await page.getByRole('button',{name:'저장',exact:true}).count(),0);
 assert.equal(await page.locator('tbody tr').first().locator('td').count(),2);
 const headingX = await page.locator('.us-description-heading').evaluate(el=>el.getBoundingClientRect().x);
 const urlWidth = await page.locator('tbody tr').first().locator('td').nth(1).evaluate(el=>el.getBoundingClientRect().width);
 await page.getByRole('button',{name:'첫 항목',exact:true}).dblclick();
 const editWidth = await page.locator('tbody tr').first().locator('td').nth(1).evaluate(el=>el.getBoundingClientRect().width);
 assert.ok(editWidth < urlWidth);
 assert.ok(Math.abs(await page.locator('.us-description-heading').evaluate(el=>el.getBoundingClientRect().x)-headingX)<1);
 assert.deepEqual(await page.locator('.us-actions button').allTextContents(),['저장','새로저장','ESC','삭제']);
 const actionStyle = await page.locator('.us-actions').first().evaluate(el=>({border:getComputedStyle(el).borderTopWidth}));
 assert.equal(actionStyle.border,'0px');
 assert.deepEqual(await page.locator('thead th').allTextContents(),['항목','설명']);
 await click('ESC');
 assert.equal(await page.locator('tbody tr').first().locator('td').nth(1).evaluate(el=>el.getBoundingClientRect().width),urlWidth);
 assert.equal(await page.locator('tbody tr').first().locator('td').count(),2);
 assert.ok(await page.locator('tbody tr').first().evaluate(el=>el.children[1].getBoundingClientRect().width > el.children[0].getBoundingClientRect().width));
 await click('첫 항목'); await page.waitForTimeout(750);
 assert.equal(await page.evaluate(()=>opens.length),1);
 await page.getByRole('button',{name:'첫 항목',exact:true}).dblclick(); await page.waitForTimeout(750);
 assert.equal(await page.evaluate(()=>opens.length),1);
 await click('ESC');
 // Double-click the cell padding, outside the link button's bounds.
 await page.locator('tbody tr').first().locator('td').first().dblclick({position:{x:3,y:3}});
 assert.equal(await page.getByRole('textbox',{name:'제목',exact:true}).count(),1);
 await click('ESC');
 await page.locator('tbody tr').first().locator('td').nth(1).dblclick({position:{x:3,y:3}});
 assert.equal(await page.getByRole('textbox',{name:'URL',exact:true}).count(),1);
 await page.waitForTimeout(750);
 assert.equal(await page.evaluate(()=>opens.length),1);
 await fill('복사','https://example.com/two'); await click('새로저장');
 assert.deepEqual((await state())[0],original); assert.equal((await state()).length,2);
 await page.getByRole('button',{name:'복사',exact:true}).dblclick(); await click('새로저장');
 assert.equal((await state()).length,2); assert.match(await page.getByRole('status').textContent(),/동일/);
 await fill('수정','https://example.com/changed'); await click('저장');
 assert.equal((await state())[1].title,'수정');
 await page.locator('.us-drag-handle').first().dragTo(page.locator('tbody tr').nth(1));
 assert.equal((await state())[0].title,'수정');
 await page.getByRole('button',{name:'수정',exact:true}).dblclick();
 page.once('dialog',dialog=>dialog.dismiss()); await click('항목 삭제'); assert.equal((await state()).length,2);
 page.once('dialog',dialog=>dialog.accept()); await click('항목 삭제'); assert.deepEqual(await state(),[original]);
 await click('항목 추가'); await fill('잘못된 주소','javascript:alert(1)'); await click('저장'); assert.equal((await state()).length,1);
 await click('ESC');
 await page.evaluate(()=>{data={items:[{id:'restored',title:'복원',url:'https://example.com/'+ 'x'.repeat(300)}]};USLinks.refresh();});
 assert.equal(await page.getByRole('button',{name:'복원',exact:true}).count(),1);
 const overflow = await page.locator('.us-link').last().evaluate(el=>({overflow:getComputedStyle(el).textOverflow,clipped:el.scrollWidth>el.clientWidth}));
 assert.equal(overflow.overflow,'ellipsis'); assert.ok(overflow.clipped);
 assert.ok(await page.evaluate(()=>saves.length>=5));
 await page.getByRole('button',{name:'복원',exact:true}).dblclick();
 const longDescription = '첫째 줄 '.repeat(100) + '\n둘째 줄\n셋째 줄\n넷째 줄';
 await page.getByRole('textbox',{name:'설명',exact:true}).fill(longDescription);
 await click('저장');
 assert.equal((await state())[0].description,longDescription.trim());
 const opensBefore = await page.evaluate(()=>opens.length);
 await page.getByRole('button',{name:'펼치기',exact:true}).waitFor({state:'visible'});
 const descriptionLayout = await page.locator('.us-description').first().evaluate(el=>{
  const text=el.querySelector('p').getBoundingClientRect(), toggle=el.querySelector('button').getBoundingClientRect();
  return {sameBottom:Math.abs(text.bottom-toggle.bottom)<2,right:toggle.left>=text.right};
 });
 assert.ok(descriptionLayout.sameBottom && descriptionLayout.right);
 await click('펼치기');
 assert.equal(await page.locator('.us-description-toggle').getAttribute('aria-expanded'),'true');
 assert.equal(await page.locator('.us-description-text').evaluate(el=>getComputedStyle(el).whiteSpace),'pre-wrap');
 await click('접기');await page.waitForTimeout(750);
 assert.equal(await page.evaluate(()=>opens.length),opensBefore);
 await page.getByRole('button',{name:'복원',exact:true}).dblclick();
 await page.getByRole('textbox',{name:'설명',exact:true}).fill('취소할 설명');await click('ESC');
 assert.match((await state())[0].description,/첫째 줄/);
 await page.getByRole('button',{name:'복원',exact:true}).dblclick();
 await fill('설명 복사','https://example.com/copy');await click('새로저장');
 assert.equal((await state())[1].description,(await state())[0].description);
 await page.evaluate(()=>USLinks.refresh());
 assert.equal(await page.locator('.us-description-text').count(),2);
 await page.evaluate(()=>{data.items=[{id:'short-lines',title:'줄바꿈 확인',url:'https://example.com',description:'짧은 첫 줄\n짧은 둘째 줄\n짧은 셋째 줄'}];USLinks.refresh();});
 await page.waitForTimeout(100);
 assert.equal(await page.locator('.us-description-text').evaluate(el=>getComputedStyle(el).whiteSpace),'normal');
 assert.equal(await page.getByRole('button',{name:'펼치기',exact:true}).count(),0);
 const descriptionOpens = await page.evaluate(()=>opens.length);
 await page.locator('.us-description-text').dblclick();
 assert.equal(await page.getByRole('textbox',{name:'설명',exact:true}).inputValue(),'짧은 첫 줄\n짧은 둘째 줄\n짧은 셋째 줄');
 assert.equal(await page.getByRole('textbox',{name:'설명',exact:true}).evaluate(el=>el===document.activeElement),true);
 await page.waitForTimeout(750);
 assert.equal(await page.evaluate(()=>opens.length),descriptionOpens);
 await click('ESC');
 const divider = await page.getByRole('separator',{name:'항목과 설명 열 너비 조절'}).boundingBox();
 await page.mouse.move(divider.x+divider.width/2,divider.y+divider.height/2);
 await page.mouse.down();await page.mouse.move(divider.x+100,divider.y+divider.height/2);await page.mouse.up();
 const resized = await page.evaluate(()=>data.titleColumnWidth);
 assert.ok(resized > 28);
 await page.evaluate(()=>USLinks.refresh());
 assert.ok(Math.abs(await page.locator('.us-title-col').evaluate(el=>parseFloat(el.style.width))-resized)<0.001);
 await page.getByRole('separator',{name:'항목과 설명 열 너비 조절'}).focus();await page.keyboard.press('Home');
 assert.equal(await page.evaluate(()=>data.titleColumnWidth),15);
 const appPage = await browser.newPage();
 await appPage.route('http://market.test/**',route=>route.fulfill({contentType:'text/html',body:fs.readFileSync('public/index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<link\b[^>]*>/gi,'')}));
 await appPage.goto('http://market.test/');
 await appPage.addScriptTag({content:fs.readFileSync('public/us-links.js','utf8')});
 await appPage.addScriptTag({content:fs.readFileSync('public/app.js','utf8')});
 const integration = await appPage.evaluate(() => {
  ensurePermanentTabs(); activateTab(US_TAB_ID);
  const adjacent = document.querySelector('[data-tab="tab_earnings"]').nextElementSibling.dataset.tab;
  tabData[US_TAB_ID].items=[{id:'integration',title:'연결 검증',url:'https://example.com'}];
  USLinks.refresh();
  const snapshot=getSerializedState(); resetDynamicTabs();
  const retained=!!document.getElementById(US_TAB_ID);
  applyData(snapshot);
  return {adjacent,retained,count:document.querySelectorAll('[data-tab="tab_us"]').length,items:getSerializedState().contents[US_TAB_ID].items};
 });
 assert.equal(integration.adjacent,'tab_us'); assert.ok(integration.retained);
 assert.equal(integration.count,1); assert.equal(integration.items[0].id,'integration');
 console.log('PASS: add, open, double-click edit, copy, duplicate rejection, update, reorder, delete confirmation, URL validation, restore, truncation, permanent tab order, settings integration');
 } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
